s0, gpu fbank and resample
wenet-e2e/wenet pull request #152
Opened 2021-02-07 04:57 UTC by qmpzzpmq

2021-02-08 01:33 UTC, robin1001 commented on examples/librispeech/s0/conf/train_conformer.yaml
> +        sample_rate: 16000
add a resample bool flag?
Maybe we will mix the 8k and 16k training by resampling or just ignoring the sample rate in the future.

2021-02-08 01:33 UTC, robin1001 requested changes
great job, please see inline.

2021-02-09 01:09 UTC, robin1001 commented on examples/librispeech/s0/conf/train_conformer.yaml
> +        sample_rate: 16000
and any results of the speedup by using GPU for fbank computation?

2021-02-18 11:28 UTC, qmpzzpmq commented
still some work could be do later
1 fbank gpu batch computing
2. torch spec augment

2021-02-19 10:53 UTC, qmpzzpmq commented
gpu fbank: 13min/100step
cpu fbank: 29min/100step

gpu: 8*V100
cpu: Intel(R) Xeon(R) Gold 6130 CPU

2021-02-19 11:11 UTC, whiteshirt0429 commented
> gpu fbank: 13min/100step
> cpu fbank: 29min/100step
> 
> gpu: 8*V100
> cpu: Intel(R) Xeon(R) Gold 6130 CPU
> dataset: personal dataset

perhaps results with dropping cache will be more reliable

2021-02-20 01:31 UTC, qmpzzpmq commented
cpu fbank: 29min/100step： 88min wich cache drop

2021-02-20 06:20 UTC, placebokkk reviewed
Thanks for this great contribution! We will do an internal benchmark to verify this improvement and merge this PR.

2021-02-20 06:20 UTC, placebokkk commented on wenet/dataset/dataset.py
> +                waveform = waveform.squeeze(0)
why do squeeze here?

2022-07-01 07:10 UTC, closed without merging