iOS runtime
wenet-e2e/wenet pull request #1549
Opened 2022-11-09 14:22 UTC by Ma-Dan

Sorry for the delayed PR, please review this version.

2022-11-10 08:18 UTC, pengzhendong requested changes

2022-11-10 08:18 UTC, pengzhendong commented on runtime/core/decoder/ios_asr_model.cc
> +//               2022 Binbin Zhang (binbzha@qq.com)
添加个人信息

2022-11-10 08:18 UTC, pengzhendong commented on runtime/core/decoder/ios_asr_model.cc
> +void IosAsrModel::InitEngineThreads(int num_threads) {
不需要的代码可以删掉

2022-11-10 08:18 UTC, pengzhendong commented on runtime/core/decoder/ios_asr_model.cc
> +#ifdef USE_GPU
USE_GPU 这个分支是不是也可以删掉

2022-11-10 08:18 UTC, pengzhendong commented on runtime/core/decoder/ios_asr_model.cc
> +#ifdef USE_GPU
同上

2022-11-10 08:18 UTC, pengzhendong commented on runtime/core/decoder/ios_asr_model.cc
> +#ifdef USE_GPU
同上

2022-11-10 08:18 UTC, pengzhendong commented on runtime/core/decoder/ios_asr_model.cc
> +#ifdef USE_GPU
同上

2022-11-10 08:18 UTC, pengzhendong commented on runtime/core/decoder/ios_asr_model.cc
> +#ifdef USE_GPU
同上

2022-11-10 08:18 UTC, pengzhendong commented on runtime/core/decoder/ios_asr_model.cc
> +#ifdef USE_GPU
同上

2022-11-10 08:18 UTC, pengzhendong commented on runtime/core/decoder/ios_asr_model.h
> +//               2022 Binbin Zhang (binbzha@qq.com)
添加作者信息

2022-11-10 08:18 UTC, pengzhendong commented on runtime/core/patch/openfst/src/bin/CMakeLists.txt
> +function (add_executable2 _name)
为什么需要编译 bin 目录下的可执行文件？

2022-11-10 08:18 UTC, pengzhendong commented on runtime/ios/WenetDemo/WenetDemo/AppDelegate.swift
> +//
参考 `ios_asr_model.cc` 来写 license 信息

2022-11-10 08:18 UTC, pengzhendong commented on runtime/ios/WenetDemo/WenetDemo/AppDelegate.swift
> +    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
swift 代码是否有相关 style 配置？例如一行不超过 80 个 char

2022-11-10 08:18 UTC, pengzhendong commented on runtime/ios/WenetDemo/WenetDemo/SceneDelegate.swift
> +//  SceneDelegate.swift
同上

2022-11-10 08:18 UTC, pengzhendong commented on runtime/ios/WenetDemo/WenetDemo/ViewController.swift
> +//  ViewController.swift
同上

2022-11-10 08:18 UTC, pengzhendong commented on runtime/ios/WenetDemo/WenetDemo/wenet/WenetDemo-Bridging-Header.h
> +//  Use this file to import your target's public headers that you would like to expose to Swift.
同上

2022-11-10 08:18 UTC, pengzhendong commented on runtime/ios/WenetDemo/WenetDemo/wenet/wenet.h
> +//  wenet.h
同上

2022-11-10 08:18 UTC, pengzhendong commented on runtime/ios/WenetDemo/WenetDemo/wenet/wenet.mm
> +//  wenet.cmm
同上

2022-11-10 08:18 UTC, pengzhendong commented on runtime/ios/api
> +../core/api
为什么需要 api？我认为可以从 CMakeLists 中删掉

2022-11-10 08:18 UTC, pengzhendong commented on runtime/ios/bin
> +../core/bin
为什么需要 bin？编译的 decoder_main 怎么用？

2022-11-10 08:18 UTC, pengzhendong commented on runtime/ios/websocket
> +../core/websocket
为什么需要 websocket

2022-11-10 08:19 UTC, pengzhendong commented
最后，还需要解决下述 lint 问题，并且写一个 README.md 描述用法。

2022-11-10 15:03 UTC, Ma-Dan commented on runtime/core/decoder/ios_asr_model.cc
> +//               2022 Binbin Zhang (binbzha@qq.com)
已按照格式添加

2022-11-10 15:03 UTC, Ma-Dan commented on runtime/core/decoder/ios_asr_model.cc
> +void IosAsrModel::InitEngineThreads(int num_threads) {
已删除

2022-11-10 15:04 UTC, Ma-Dan commented on runtime/core/decoder/ios_asr_model.cc
> +#ifdef USE_GPU
已删除

2022-11-10 15:04 UTC, Ma-Dan commented on runtime/core/decoder/ios_asr_model.cc
> +#ifdef USE_GPU
已删除

2022-11-10 15:04 UTC, Ma-Dan commented on runtime/core/decoder/ios_asr_model.cc
> +#ifdef USE_GPU
已删除

2022-11-10 15:04 UTC, Ma-Dan commented on runtime/core/decoder/ios_asr_model.cc
> +#ifdef USE_GPU
已删除

2022-11-10 15:05 UTC, Ma-Dan commented on runtime/core/decoder/ios_asr_model.cc
> +#ifdef USE_GPU
已删除

2022-11-10 15:05 UTC, Ma-Dan commented on runtime/core/decoder/ios_asr_model.h
> +//               2022 Binbin Zhang (binbzha@qq.com)
已添加

2022-11-10 15:05 UTC, Ma-Dan commented on runtime/ios/WenetDemo/WenetDemo/AppDelegate.swift
> +//
已添加

2022-11-10 15:06 UTC, Ma-Dan commented on runtime/ios/WenetDemo/WenetDemo/SceneDelegate.swift
> +//  SceneDelegate.swift
已添加

2022-11-10 15:10 UTC, Ma-Dan commented on runtime/ios/WenetDemo/WenetDemo/wenet/WenetDemo-Bridging-Header.h
> +//  Use this file to import your target's public headers that you would like to expose to Swift.
已添加

2022-11-10 15:10 UTC, Ma-Dan commented on runtime/ios/WenetDemo/WenetDemo/wenet/wenet.mm
> +//  wenet.cmm
已添加

2022-11-10 15:10 UTC, Ma-Dan commented on runtime/ios/api
> +../core/api
已删除

2022-11-10 15:10 UTC, Ma-Dan commented on runtime/ios/bin
> +../core/bin
已删除

2022-11-10 15:10 UTC, Ma-Dan commented on runtime/ios/websocket
> +../core/websocket
已删除

2022-11-10 15:15 UTC, Ma-Dan commented
目前还有如下几个问题：
- [ ] 删除这些之后，需要处理的target少了很多，编译也节省了很多时间和空间，但是依然还剩下fst相关的6个execuatable target，这个手动处理要看看能不能通过openfst的cmakefile patch或者其他方法去掉
- [ ] swift 代码有相关 style 配置
- [ ] lint

2022-11-10 15:26 UTC, pengzhendong requested changes

2022-11-10 15:26 UTC, pengzhendong commented on runtime/ios/README.md
> +cmake .. -G Xcode -DTORCH=OFF -DONNX=OFF -DIOS=ON -DGRAPH_TOOLS=ON -DBUILD_TESTING=OFF -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DPLATFORM=OS64 -DENABLE_BITCODE=FALSE
没有必要编译 GRAPH_TOOLS，请设置为 OFF

2022-11-10 15:26 UTC, pengzhendong commented on runtime/ios/CMakeLists.txt
> +if(GRPC)
可以删除 GRPC 相关选项

2022-11-10 15:45 UTC, Ma-Dan commented on runtime/ios/README.md
> +cmake .. -G Xcode -DTORCH=OFF -DONNX=OFF -DIOS=ON -DGRAPH_TOOLS=ON -DBUILD_TESTING=OFF -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DPLATFORM=OS64 -DENABLE_BITCODE=FALSE
关闭GRAPH_TOOLS之后，就无需之前的第2步手动删除了

2022-11-10 15:50 UTC, Ma-Dan commented on runtime/ios/CMakeLists.txt
> +if(GRPC)
已删除

2022-11-11 02:11 UTC, robin1001 commented on runtime/core/decoder/ios_asr_model.cc
> +// you may not use this file except in compliance with the License.
what's the difference of ios_asr_model and torch_asr_model

2022-11-11 11:40 UTC, Ma-Dan commented on runtime/core/decoder/ios_asr_model.cc
> +// you may not use this file except in compliance with the License.
区别并不大，只是一点包含文件和流程细节的差异，也可以用宏的方式合并到一个文件里面，但那样又感觉可能把ifdef弄的过于复杂。

2022-11-11 14:53 UTC, robin1001 commented on runtime/core/decoder/ios_asr_model.cc
> +// you may not use this file except in compliance with the License.
文件和流程细节的差异具体是指？

2022-11-12 00:39 UTC, Ma-Dan commented on runtime/core/decoder/ios_asr_model.cc
> +// you may not use this file except in compliance with the License.
#include去掉了一个ios LibTorch没有的头文件，然后删掉了一些初始化。
我正在将它合并到torch_asr_model中。

2022-11-12 01:21 UTC, robin1001 commented on runtime/core/decoder/ios_asr_model.cc
> +// you may not use this file except in compliance with the License.
okay，it's better if we combine it.

2022-11-12 01:27 UTC, Ma-Dan commented on runtime/core/decoder/ios_asr_model.cc
> +// you may not use this file except in compliance with the License.
已经合并完成，请review一下

2022-11-12 13:36 UTC, Ma-Dan commented on runtime/ios/WenetDemo/WenetDemo/AppDelegate.swift
> +    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
已按照style修改

2022-11-14 02:19 UTC, robin1001 approved these changes

2022-11-14 02:20 UTC, robin1001 commented
Great job! And I wonder if there is some video demo?

2022-11-14 02:20 UTC, merged