refactor(yaml): Config ctc/cmvn/tokenizer in train.yaml
wenet-e2e/wenet pull request #2205
Opened 2023-12-08 07:26 UTC by xingchensong

将模型相关的配置从train args移动到yaml

2023-12-08 12:42 UTC, Mddct commented
great work

2023-12-08 12:53 UTC, Mddct submitted a review, later dismissed

2023-12-08 12:53 UTC, Mddct commented
TODO 
- [ ] paraformer special tokens @Mddct 
- [ ] tokenizer check special tokens valid @Mddct

2023-12-08 12:54 UTC, xingchensong commented
稍等我验证下解码

2023-12-08 12:59 UTC, xingchensong commented
![image](https://github.com/wenet-e2e/wenet/assets/13466943/5e4603e7-8338-4191-aae3-210545efb771)

解码通过

2023-12-08 13:00 UTC, xingchensong commented
变动比较大， @robin1001 binbin必须看下

2023-12-08 13:14 UTC, robin1001 requested changes
周哥，这个改动比较大，功能也很杂，强烈建议分开提 PR，每个 PR 只做一个功能，来自 Google 软件实践指南中的建议。

2023-12-08 13:49 UTC, xingchensong commented
记一个TODO，后面runtime也要针对special id做对应的修改，比如blanckid不是0，sos不是vocabsize-1等

2023-12-10 03:58 UTC, xingchensong commented
本PR的核心诉求：

与模型相关的配置尽量都在yaml中，不放在training args里

![image](https://github.com/wenet-e2e/wenet/assets/13466943/3cf5ba11-4958-41a6-8a44-d4deda292a03)

2023-12-12 09:05 UTC, xingchensong commented
模型转换脚本（sos从vocabsize-1变成2）

```py
import torch                                                                                                                                                                                                                  [3/528]

old_state = torch.load('/mnt/d/BaiduSyncdisk/downloads/ckpt/20210601_u2++_conformer_exp_aishell/final.pt')
new_state = {}
change_list = ['decoder.left_decoder.output_layer.weight',
               'decoder.left_decoder.output_layer.bias',
               'decoder.left_decoder.embed.0.weight',
               'decoder.right_decoder.output_layer.weight',
               'decoder.right_decoder.output_layer.bias',
               'decoder.right_decoder.embed.0.weight',
               'ctc.ctc_lo.weight',
               'ctc.ctc_lo.bias']
for key in old_state.keys():
    if key in change_list:
        print("processing {}, {}".format(key, old_state[key].size()))
        tensor = old_state[key]
        new_tensor = torch.zeros_like(tensor)
        if len(tensor.size()) == 2:  # weight
            new_tensor[:2, :] = tensor[:2, :]
            new_tensor[2, :] = tensor[-1, :]
            new_tensor[3:, :] = tensor[2:-1, :]
        elif len(tensor.size()) == 1:  # bias
            new_tensor[:2] = tensor[:2]
            new_tensor[2] = tensor[-1]
            new_tensor[3:] = tensor[2:-1]
        else:
            raise NotImplementedError
        new_state[key] = new_tensor
    elif "concat_linear" in key:
        continue
    else:
        new_state[key] = old_state[key]

torch.save(new_state, "/mnt/d/BaiduSyncdisk/downloads/ckpt/20210601_u2++_conformer_exp_aishell/final.sos2.pt")
```

转换后可以成功解码
![image](https://github.com/wenet-e2e/wenet/assets/13466943/60f31b93-2e50-4f68-8925-3f22b18709e4)

2023-12-12 09:52 UTC, xingchensong commented
解码结果一致

![image](https://github.com/wenet-e2e/wenet/assets/13466943/e05dc28f-7c7d-4f1d-accd-26e285c04c14)

![image](https://github.com/wenet-e2e/wenet/assets/13466943/dfc4be4a-eaea-4575-a131-9ee0c39a9a1f)

2023-12-12 11:38 UTC, Mddct submitted a review, later dismissed

2023-12-13 04:47 UTC, Mddct approved these changes

2023-12-13 04:58 UTC, robin1001 approved these changes

2023-12-13 04:58 UTC, merged