add recognize_onnx.py
wenet-e2e/wenet pull request #761
Opened 2021-11-04 12:00 UTC by Slyne

Signed-off-by: slyned <slyned@nvidia.com>

Add script for recognizing the exported onnx models.
Both GPU & CPU are supported in onnxruntime.

Usage:
```bash
python3 wenet/bin/recognize_onnx.py --config=20210618_u2pp_conformer_exp/train.yaml --test_data=raw_wav/test/data.list --gpu=0 --dict=20210618_u2pp_conformer_exp/words.txt --mode=attention_rescoring --reverse_weight=0.4 --ctc_weight=0.1 --result_file=./att_res_result.txt --encoder_onnx=onnx_model/encoder.onnx --decoder_onnx=onnx_model/decoder.onnx
```

2021-11-04 12:04 UTC, Slyne commented
@robin1001 @pengzhendong

2021-11-04 12:06 UTC, pengzhendong requested changes

2021-11-04 12:06 UTC, pengzhendong commented on wenet/bin/recognize_onnx.py
> +# Copyright (c) 2020 Mobvoi Inc. (authors: Binbin Zhang, Xiaoyu Chen, Di Wu)
nvidia

2021-11-06 03:17 UTC, robin1001 approved these changes

2021-11-06 03:18 UTC, merged